<?php
if(!defined('IMPARENT')){exit();} // No direct access
if(!defined('JSTORE')){exit();} // No direct access

function currency_lists(){
	$currencies = array();
	$currencies[] = (object) array('CODE' => 'AFN ','SYMBOL' =>'','TEXT' => 'Afghanistan, Afghani');
	$currencies[] = (object) array('CODE' => 'ALL ','SYMBOL' =>'','TEXT' => 'Albania, Lek');
	$currencies[] = (object) array('CODE' => 'DZD ','SYMBOL' =>'','TEXT' => 'Algeria, Dinar');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'America (United States), Dollar');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'American Samoa, United States Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Andorra, Euro');
	$currencies[] = (object) array('CODE' => 'AOA ','SYMBOL' =>'','TEXT' => 'Angola, Kwanza');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'Anguilla, East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'Antigua and Barbuda, East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'ARS ','SYMBOL' =>'','TEXT' => 'Argentina, Peso');
	$currencies[] = (object) array('CODE' => 'AMD ','SYMBOL' =>'','TEXT' => 'Armenia, Dram');
	$currencies[] = (object) array('CODE' => 'AWG ','SYMBOL' =>'','TEXT' => 'Aruba, Guilder');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Ashmore and Cartier Islands, Australia Dollar');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Australia, Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Austria, Euro');
	$currencies[] = (object) array('CODE' => 'AZN ','SYMBOL' =>'','TEXT' => 'Azerbaijan, New Manat');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Azores, Euro');
	$currencies[] = (object) array('CODE' => 'BSD ','SYMBOL' =>'','TEXT' => 'Bahamas, Dollar');
	$currencies[] = (object) array('CODE' => 'BHD ','SYMBOL' =>'','TEXT' => 'Bahrain, Dinar');
	$currencies[] = (object) array('CODE' => 'BBD ','SYMBOL' =>'','TEXT' => 'Bajan (Barbados), Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Balearic Islands, Euro');
	$currencies[] = (object) array('CODE' => 'BDT ','SYMBOL' =>'','TEXT' => 'Bangladesh, Taka');
	$currencies[] = (object) array('CODE' => 'BBD ','SYMBOL' =>'','TEXT' => 'Barbados, Dollar');
	$currencies[] = (object) array('CODE' => 'BYR ','SYMBOL' =>'','TEXT' => 'Belarus, Ruble');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Belgium, Euro');
	$currencies[] = (object) array('CODE' => 'BZD ','SYMBOL' =>'','TEXT' => 'Belize, Dollar');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Benin, CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'BMD ','SYMBOL' =>'','TEXT' => 'Bermuda, Dollar');
	$currencies[] = (object) array('CODE' => 'INR ','SYMBOL' =>'','TEXT' => 'Bhutan, India Rupee');
	$currencies[] = (object) array('CODE' => 'BTN ','SYMBOL' =>'','TEXT' => 'Bhutan, Ngultrum');
	$currencies[] = (object) array('CODE' => 'BOB ','SYMBOL' =>'','TEXT' => 'Bolivia, Boliviano');
	$currencies[] = (object) array('CODE' => 'ANG ','SYMBOL' =>'','TEXT' => 'Bonaire, Netherlands Antilles Guilder');
	$currencies[] = (object) array('CODE' => 'BAM ','SYMBOL' =>'','TEXT' => 'Bosnia and Herzegovina, Convertible Marka');
	$currencies[] = (object) array('CODE' => 'BWP ','SYMBOL' =>'','TEXT' => 'Botswana, Pula');
	$currencies[] = (object) array('CODE' => 'BRL ','SYMBOL' =>'','TEXT' => 'Brazil, Real');
	$currencies[] = (object) array('CODE' => 'GBP ','SYMBOL' =>'','TEXT' => 'Britain (United Kingdom), Pound');
	$currencies[] = (object) array('CODE' => 'GBP ','SYMBOL' =>'','TEXT' => 'British Indian Ocean Territory, United Kingdom Pound');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'British Indian Ocean Territory, United States Dollar');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'British Virgin Islands, United States Dollar');
	$currencies[] = (object) array('CODE' => 'BND ','SYMBOL' =>'','TEXT' => 'Brunei, Dollar');
	$currencies[] = (object) array('CODE' => 'SGD ','SYMBOL' =>'','TEXT' => 'Brunei, Singapore Dollar');
	$currencies[] = (object) array('CODE' => 'BGN ','SYMBOL' =>'','TEXT' => 'Bulgaria, Lev');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Burkina Faso, CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'MMK ','SYMBOL' =>'','TEXT' => 'Burma (Myanmar), Kyat');
	$currencies[] = (object) array('CODE' => 'BIF ','SYMBOL' =>'','TEXT' => 'Burundi, Franc');
	$currencies[] = (object) array('CODE' => 'KHR ','SYMBOL' =>'','TEXT' => 'Cambodia, Riel');
	$currencies[] = (object) array('CODE' => 'XAF ','SYMBOL' =>'','TEXT' => 'Cameroon, CFA Franc BEAC');
	$currencies[] = (object) array('CODE' => 'CAD ','SYMBOL' =>'','TEXT' => 'Canada, Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Canary Islands, Euro');
	$currencies[] = (object) array('CODE' => 'CVE ','SYMBOL' =>'','TEXT' => 'Cape Verde, Escudo');
	$currencies[] = (object) array('CODE' => 'KYD ','SYMBOL' =>'','TEXT' => 'Cayman Islands, Dollar');
	$currencies[] = (object) array('CODE' => 'XAF ','SYMBOL' =>'','TEXT' => 'Central African Republic, CFA Franc BEAC');
	$currencies[] = (object) array('CODE' => 'XAF ','SYMBOL' =>'','TEXT' => 'CFA Communauté Financière Africaine BEAC Franc');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'CFA Communauté Financière Africaine BCEAO Franc');
	$currencies[] = (object) array('CODE' => 'XAF ','SYMBOL' =>'','TEXT' => 'Chad, CFA Franc BEAC');
	$currencies[] = (object) array('CODE' => 'CLP ','SYMBOL' =>'','TEXT' => 'Chile, Peso');
	$currencies[] = (object) array('CODE' => 'CNY ','SYMBOL' =>'','TEXT' => 'China, Yuan Renminbi');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Christmas Island, Australia Dollar');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Cocos (Keeling Islands, Australia Dollar');
	$currencies[] = (object) array('CODE' => 'COP ','SYMBOL' =>'','TEXT' => 'Colombia, Peso');
	$currencies[] = (object) array('CODE' => 'XAF ','SYMBOL' =>'','TEXT' => 'Communauté Financière Africaine BEAC Franc');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Communauté Financière Africaine BCEAO Franc');
	$currencies[] = (object) array('CODE' => 'KMF ','SYMBOL' =>'','TEXT' => 'Comoros, Franc');
	$currencies[] = (object) array('CODE' => 'XPF ','SYMBOL' =>'','TEXT' => 'Comptoirs Français du Pacifique Franc');
	$currencies[] = (object) array('CODE' => 'XAF ','SYMBOL' =>'','TEXT' => 'Congo/Brazzaville, CFA Franc BEAC');
	$currencies[] = (object) array('CODE' => 'CDF ','SYMBOL' =>'','TEXT' => 'Congo/Kinshasa, Franc');
	$currencies[] = (object) array('CODE' => 'NZD ','SYMBOL' =>'','TEXT' => 'Cook Islands, New Zealand Dollar');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Coral Sea Islands, Australia Dollar');
	$currencies[] = (object) array('CODE' => 'CRC ','SYMBOL' =>'','TEXT' => 'Costa Rica, Colon');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Côte d\'Ivoire, CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'HRK ','SYMBOL' =>'','TEXT' => 'Croatia, Kuna');
	$currencies[] = (object) array('CODE' => 'CUC ','SYMBOL' =>'','TEXT' => 'Cuba, Convertible Peso');
	$currencies[] = (object) array('CODE' => 'CUP ','SYMBOL' =>'','TEXT' => 'Cuba, Peso');
	$currencies[] = (object) array('CODE' => 'ANG ','SYMBOL' =>'','TEXT' => 'Curaço, Netherlands Antilles Guilder');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Cyprus, Euro');
	$currencies[] = (object) array('CODE' => 'CZK ','SYMBOL' =>'','TEXT' => 'Czech Republic, Koruna');
	$currencies[] = (object) array('CODE' => 'DKK ','SYMBOL' =>'','TEXT' => 'Denmark, Krone');
	$currencies[] = (object) array('CODE' => 'DJF ','SYMBOL' =>'','TEXT' => 'Djibouti, Franc');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'Dominica, East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'DOP ','SYMBOL' =>'','TEXT' => 'Dominican Republic, Peso');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Dutch (Netherlands), Euro');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'East Timor, United States Dollar');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Ecuador, United States Dollar');
	$currencies[] = (object) array('CODE' => 'EGP ','SYMBOL' =>'','TEXT' => 'Egypt, Pound');
	$currencies[] = (object) array('CODE' => 'SVC ','SYMBOL' =>'','TEXT' => 'El Salvador, Colon');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'El Salvador, United States Dollar');
	$currencies[] = (object) array('CODE' => 'GBP ','SYMBOL' =>'','TEXT' => 'England (United Kingdom), Pound');
	$currencies[] = (object) array('CODE' => 'XAF ','SYMBOL' =>'','TEXT' => 'Equatorial Guinea, CFA Franc BEAC');
	$currencies[] = (object) array('CODE' => 'ERN ','SYMBOL' =>'','TEXT' => 'Eritrea, Nakfa');
	$currencies[] = (object) array('CODE' => 'EEK ','SYMBOL' =>'','TEXT' => 'Estonia, Kroon');
	$currencies[] = (object) array('CODE' => 'ETB ','SYMBOL' =>'','TEXT' => 'Ethiopia, Birr');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Euro');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Europa Island, Euro');
	$currencies[] = (object) array('CODE' => 'FKP ','SYMBOL' =>'','TEXT' => 'Falkland Islands, Pound');
	$currencies[] = (object) array('CODE' => 'DKK ','SYMBOL' =>'','TEXT' => 'Faroe Islands, Denmark Krone');
	$currencies[] = (object) array('CODE' => 'FJD ','SYMBOL' =>'','TEXT' => 'Fiji, Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Finland, Euro');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'France, Euro');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'French Guiana, Euro');
	$currencies[] = (object) array('CODE' => 'XPF ','SYMBOL' =>'','TEXT' => 'French Polynesia, Comptoirs Français du Pacifique Franc');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'French Southern and Antarctic Lands, Euro');
	$currencies[] = (object) array('CODE' => 'XAF ','SYMBOL' =>'','TEXT' => 'Gabon, CFA Franc BEAC');
	$currencies[] = (object) array('CODE' => 'GMD ','SYMBOL' =>'','TEXT' => 'Gambia, Dalasi');
	$currencies[] = (object) array('CODE' => 'ILS ','SYMBOL' =>'','TEXT' => 'Gaza Strip, Israel New Shekel');
	$currencies[] = (object) array('CODE' => 'GEL ','SYMBOL' =>'','TEXT' => 'Georgia, Lari');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Germany, Euro');
	$currencies[] = (object) array('CODE' => 'GHS ','SYMBOL' =>'','TEXT' => 'Ghana, Cedi');
	$currencies[] = (object) array('CODE' => 'GIP ','SYMBOL' =>'','TEXT' => 'Gibraltar, Pound');
	$currencies[] = (object) array('CODE' => 'XAU ','SYMBOL' =>'','TEXT' => 'Gold Ounce');
	$currencies[] = (object) array('CODE' => 'GBP ','SYMBOL' =>'','TEXT' => 'Great Britain (United Kingdom), Pound');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Greece, Euro');
	$currencies[] = (object) array('CODE' => 'DKK ','SYMBOL' =>'','TEXT' => 'Greenland, Denmark Krone');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'Grenada, East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Guadeloupe, Euro');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Guam, United States Dollar');
	$currencies[] = (object) array('CODE' => 'GTQ ','SYMBOL' =>'','TEXT' => 'Guatemala, Quetzal');
	$currencies[] = (object) array('CODE' => 'GGP ','SYMBOL' =>'','TEXT' => 'Guernsey, Pound');
	$currencies[] = (object) array('CODE' => 'GNF ','SYMBOL' =>'','TEXT' => 'Guinea, Franc');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Guinea-Bissau, CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'GYD ','SYMBOL' =>'','TEXT' => 'Guyana, Dollar');
	$currencies[] = (object) array('CODE' => 'HTG ','SYMBOL' =>'','TEXT' => 'Haiti, Gourde');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Holland (Netherlands), Euro');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Holy See (Vatican City), Euro');
	$currencies[] = (object) array('CODE' => 'HNL ','SYMBOL' =>'','TEXT' => 'Honduras, Lempira');
	$currencies[] = (object) array('CODE' => 'HKD ','SYMBOL' =>'','TEXT' => 'Hong Kong, Dollar');
	$currencies[] = (object) array('CODE' => 'HUF ','SYMBOL' =>'','TEXT' => 'Hungary, Forint');
	$currencies[] = (object) array('CODE' => 'ISK ','SYMBOL' =>'','TEXT' => 'Iceland, Krona');
	$currencies[] = (object) array('CODE' => 'INR ','SYMBOL' =>'','TEXT' => 'India, Rupee');
	$currencies[] = (object) array('CODE' => 'IDR ','SYMBOL' =>'','TEXT' => 'Indonesia, Rupiah');
	$currencies[] = (object) array('CODE' => 'XDR ','SYMBOL' =>'','TEXT' => 'International Monetary Fund Special Drawing Right');
	$currencies[] = (object) array('CODE' => 'IRR ','SYMBOL' =>'','TEXT' => 'Iran, Rial');
	$currencies[] = (object) array('CODE' => 'IQD ','SYMBOL' =>'','TEXT' => 'Iraq, Dinar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Ireland, Euro');
	$currencies[] = (object) array('CODE' => 'FKP ','SYMBOL' =>'','TEXT' => 'Islas Malvinas (Falkland Islands), Pound');
	$currencies[] = (object) array('CODE' => 'IMP ','SYMBOL' =>'','TEXT' => 'Isle of Man, Pound');
	$currencies[] = (object) array('CODE' => 'ILS ','SYMBOL' =>'','TEXT' => 'Israel, New Shekel');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Italy, Euro');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Ivory Coast (Côte d\'Ivoire), CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'JMD ','SYMBOL' =>'','TEXT' => 'Jamaica, Dollar');
	$currencies[] = (object) array('CODE' => 'JPY ','SYMBOL' =>'','TEXT' => 'Japan, Yen');
	$currencies[] = (object) array('CODE' => 'JEP ','SYMBOL' =>'','TEXT' => 'Jersey, Pound');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Johnson, United States Dollar');
	$currencies[] = (object) array('CODE' => 'JOD ','SYMBOL' =>'','TEXT' => 'Jordan, Dinar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Juan de Nova, Euro');
	$currencies[] = (object) array('CODE' => 'KZT ','SYMBOL' =>'','TEXT' => 'Kazakhstan, Tenge');
	$currencies[] = (object) array('CODE' => 'KES ','SYMBOL' =>'','TEXT' => 'Kenya, Shilling');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Kiribati, Australia Dollar');
	$currencies[] = (object) array('CODE' => 'KWD ','SYMBOL' =>'','TEXT' => 'Kuwait, Dinar');
	$currencies[] = (object) array('CODE' => 'KGS ','SYMBOL' =>'','TEXT' => 'Kyrgyzstan, Som');
	$currencies[] = (object) array('CODE' => 'LAK ','SYMBOL' =>'','TEXT' => 'Laos, Kip');
	$currencies[] = (object) array('CODE' => 'LVL ','SYMBOL' =>'','TEXT' => 'Latvia, Lat');
	$currencies[] = (object) array('CODE' => 'LBP ','SYMBOL' =>'','TEXT' => 'Lebanon, Pound');
	$currencies[] = (object) array('CODE' => 'LSL ','SYMBOL' =>'','TEXT' => 'Lesotho, Loti');
	$currencies[] = (object) array('CODE' => 'LRD ','SYMBOL' =>'','TEXT' => 'Liberia, Dollar');
	$currencies[] = (object) array('CODE' => 'LYD ','SYMBOL' =>'','TEXT' => 'Libya, Dinar');
	$currencies[] = (object) array('CODE' => 'CHF ','SYMBOL' =>'','TEXT' => 'Liechtenstein, Switzerland Franc');
	$currencies[] = (object) array('CODE' => 'LTL ','SYMBOL' =>'','TEXT' => 'Lithuania, Litas');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Luxembourg, Euro');
	$currencies[] = (object) array('CODE' => 'MOP ','SYMBOL' =>'','TEXT' => 'Macau, Pataca');
	$currencies[] = (object) array('CODE' => 'MKD ','SYMBOL' =>'','TEXT' => 'Macedonia, Denar');
	$currencies[] = (object) array('CODE' => 'MGA ','SYMBOL' =>'','TEXT' => 'Madagascar, Ariary');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Madeira Islands, Euro');
	$currencies[] = (object) array('CODE' => 'MWK ','SYMBOL' =>'','TEXT' => 'Malawi, Kwacha');
	$currencies[] = (object) array('CODE' => 'MYR ','SYMBOL' =>'','TEXT' => 'Malaysia, Ringgit');
	$currencies[] = (object) array('CODE' => 'MVR ','SYMBOL' =>'','TEXT' => 'Maldives, Rufiyaa');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Mali, CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Malta, Euro');
	$currencies[] = (object) array('CODE' => 'FKP ','SYMBOL' =>'','TEXT' => 'Malvinas (Falkland Islands), Pound');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Marshall Islands, United States Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Martinique, Euro');
	$currencies[] = (object) array('CODE' => 'MRO ','SYMBOL' =>'','TEXT' => 'Mauritania, Ouguiya');
	$currencies[] = (object) array('CODE' => 'MUR ','SYMBOL' =>'','TEXT' => 'Mauritius, Rupee');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Mayotte, Euro');
	$currencies[] = (object) array('CODE' => 'MXN ','SYMBOL' =>'','TEXT' => 'Mexico, Peso');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Micronesia, United States Dollar');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Midway Islands, United States Dollar');
	$currencies[] = (object) array('CODE' => 'MDL ','SYMBOL' =>'','TEXT' => 'Moldova, Leu');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Monaco, Euro');
	$currencies[] = (object) array('CODE' => 'MNT ','SYMBOL' =>'','TEXT' => 'Mongolia, Tughrik');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Montenegro, Euro');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'Montserrat, East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'MAD ','SYMBOL' =>'','TEXT' => 'Morocco, Dirham');
	$currencies[] = (object) array('CODE' => 'MZN ','SYMBOL' =>'','TEXT' => 'Mozambique, Metical');
	$currencies[] = (object) array('CODE' => 'MMK ','SYMBOL' =>'','TEXT' => 'Myanmar (Burma), Kyat');
	$currencies[] = (object) array('CODE' => 'NAD ','SYMBOL' =>'','TEXT' => 'Namibia, Dollar');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Nauru, Australia Dollar');
	$currencies[] = (object) array('CODE' => 'HTG ','SYMBOL' =>'','TEXT' => 'Navassa, Haiti Gourde');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Navassa, United States Dollar');
	$currencies[] = (object) array('CODE' => 'NPR ','SYMBOL' =>'','TEXT' => 'Nepal, Rupee');
	$currencies[] = (object) array('CODE' => 'ANG ','SYMBOL' =>'','TEXT' => 'Netherlands Antilles, Guilder');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Netherlands, Euro');
	$currencies[] = (object) array('CODE' => 'XPF ','SYMBOL' =>'','TEXT' => 'New Caledonia, Comptoirs Français du Pacifique Franc');
	$currencies[] = (object) array('CODE' => 'NZD ','SYMBOL' =>'','TEXT' => 'New Zealand, Dollar');
	$currencies[] = (object) array('CODE' => 'NIO ','SYMBOL' =>'','TEXT' => 'Nicaragua, Cordoba');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Niger, CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'NGN ','SYMBOL' =>'','TEXT' => 'Nigeria, Naira');
	$currencies[] = (object) array('CODE' => 'NZD ','SYMBOL' =>'','TEXT' => 'Niue, New Zealand Dollar');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Norfolk Island, Australia Dollar');
	$currencies[] = (object) array('CODE' => 'KPW ','SYMBOL' =>'','TEXT' => 'North Korea, Won');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Northern Mariana Islands, United States Dollar');
	$currencies[] = (object) array('CODE' => 'NOK ','SYMBOL' =>'','TEXT' => 'Norway, Krone');
	$currencies[] = (object) array('CODE' => 'OMR ','SYMBOL' =>'','TEXT' => 'Oman, Rial');
	$currencies[] = (object) array('CODE' => 'PKR ','SYMBOL' =>'','TEXT' => 'Pakistan, Rupee');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Palau, United States Dollar');
	$currencies[] = (object) array('CODE' => 'XPD ','SYMBOL' =>'','TEXT' => 'Palladium Ounce');
	$currencies[] = (object) array('CODE' => 'PAB ','SYMBOL' =>'','TEXT' => 'Panama, Balboa');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Panama, United States Dollar');
	$currencies[] = (object) array('CODE' => 'PGK ','SYMBOL' =>'','TEXT' => 'Papua New Guinea, Kina');
	$currencies[] = (object) array('CODE' => 'CNY ','SYMBOL' =>'','TEXT' => 'Paracel Islands, China Yuan Renminbi');
	$currencies[] = (object) array('CODE' => 'VND ','SYMBOL' =>'','TEXT' => 'Paracel Islands, Vietnam Dong');
	$currencies[] = (object) array('CODE' => 'PYG ','SYMBOL' =>'','TEXT' => 'Paraguay, Guarani');
	$currencies[] = (object) array('CODE' => 'PEN ','SYMBOL' =>'','TEXT' => 'Peru, Nuevo Sol');
	$currencies[] = (object) array('CODE' => 'PHP ','SYMBOL' =>'','TEXT' => 'Philippines, Peso');
	$currencies[] = (object) array('CODE' => 'NZD ','SYMBOL' =>'','TEXT' => 'Pitcairn, New Zealand Dollar');
	$currencies[] = (object) array('CODE' => 'XPT ','SYMBOL' =>'','TEXT' => 'Platinum Ounce');
	$currencies[] = (object) array('CODE' => 'PLN ','SYMBOL' =>'','TEXT' => 'Poland, Zloty');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Portugal, Euro');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Puerto Rico, United States Dollar');
	$currencies[] = (object) array('CODE' => 'QAR ','SYMBOL' =>'','TEXT' => 'Qatar, Riyal');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Réunion, Euro');
	$currencies[] = (object) array('CODE' => 'RON ','SYMBOL' =>'','TEXT' => 'Romania, New Leu');
	$currencies[] = (object) array('CODE' => 'RUB ','SYMBOL' =>'','TEXT' => 'Russia, Ruble');
	$currencies[] = (object) array('CODE' => 'RWF ','SYMBOL' =>'','TEXT' => 'Rwanda, Franc');
	$currencies[] = (object) array('CODE' => 'ANG ','SYMBOL' =>'','TEXT' => 'Saba, Netherlands Antilles Guilder');
	$currencies[] = (object) array('CODE' => 'SHP ','SYMBOL' =>'','TEXT' => 'Saint Helena, Pound');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'Saint Kitts and Nevis, East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'Saint Lucia, East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Saint Pierre and Miquelon, Euro');
	$currencies[] = (object) array('CODE' => 'XCD ','SYMBOL' =>'','TEXT' => 'Saint Vincent and The Grenadines, East Caribbean Dollar');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Saint-Martin, Euro');
	$currencies[] = (object) array('CODE' => 'WST ','SYMBOL' =>'','TEXT' => 'Samoa, Tala');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'San Marino, Euro');
	$currencies[] = (object) array('CODE' => 'STD ','SYMBOL' =>'','TEXT' => 'São Tome and Principe, Dobra');
	$currencies[] = (object) array('CODE' => 'SAR ','SYMBOL' =>'','TEXT' => 'Saudi Arabia, Riyal');
	$currencies[] = (object) array('CODE' => 'GBP ','SYMBOL' =>'','TEXT' => 'Scotland (United Kingdom), Pound');
	$currencies[] = (object) array('CODE' => 'SPL ','SYMBOL' =>'','TEXT' => 'Seborga, Luigino');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Senegal, CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'RSD ','SYMBOL' =>'','TEXT' => 'Serbia, Dinar');
	$currencies[] = (object) array('CODE' => 'SCR ','SYMBOL' =>'','TEXT' => 'Seychelles, Rupee');
	$currencies[] = (object) array('CODE' => 'SLL ','SYMBOL' =>'','TEXT' => 'Sierra Leone, Leone');
	$currencies[] = (object) array('CODE' => 'XAG ','SYMBOL' =>'','TEXT' => 'Silver Ounce');
	$currencies[] = (object) array('CODE' => 'SGD ','SYMBOL' =>'','TEXT' => 'Singapore, Dollar');
	$currencies[] = (object) array('CODE' => 'ANG ','SYMBOL' =>'','TEXT' => 'Sint Eustatius, Netherlands Antilles Guilder');
	$currencies[] = (object) array('CODE' => 'ANG ','SYMBOL' =>'','TEXT' => 'Sint Maarten, Netherlands Antilles Guilder');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Slovakia, Euro');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Slovenia, Euro');
	$currencies[] = (object) array('CODE' => 'SBD ','SYMBOL' =>'','TEXT' => 'Solomon Islands, Dollar');
	$currencies[] = (object) array('CODE' => 'SOS ','SYMBOL' =>'','TEXT' => 'Somalia, Shilling');
	$currencies[] = (object) array('CODE' => 'ZAR ','SYMBOL' =>'','TEXT' => 'South Africa, Rand');
	$currencies[] = (object) array('CODE' => 'GBP ','SYMBOL' =>'','TEXT' => 'South Georgia, United Kingdom Pound');
	$currencies[] = (object) array('CODE' => 'KRW ','SYMBOL' =>'','TEXT' => 'South Korea, Won');
	$currencies[] = (object) array('CODE' => 'GBP ','SYMBOL' =>'','TEXT' => 'South Sandwich Islands, United Kingdom Pound');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Spain, Euro');
	$currencies[] = (object) array('CODE' => 'LKR ','SYMBOL' =>'','TEXT' => 'Sri Lanka, Rupee');
	$currencies[] = (object) array('CODE' => 'SDG ','SYMBOL' =>'','TEXT' => 'Sudan, Pound');
	$currencies[] = (object) array('CODE' => 'SRD ','SYMBOL' =>'','TEXT' => 'Suriname, Dollar');
	$currencies[] = (object) array('CODE' => 'NOK ','SYMBOL' =>'','TEXT' => 'Svalbard and Jan Mayen, Norway Krone');
	$currencies[] = (object) array('CODE' => 'SZL ','SYMBOL' =>'','TEXT' => 'Swaziland, Lilangeni');
	$currencies[] = (object) array('CODE' => 'ZAR ','SYMBOL' =>'','TEXT' => 'Swaziland, South Africa Rand');
	$currencies[] = (object) array('CODE' => 'SEK ','SYMBOL' =>'','TEXT' => 'Sweden, Krona');
	$currencies[] = (object) array('CODE' => 'CHF ','SYMBOL' =>'','TEXT' => 'Switzerland, Franc');
	$currencies[] = (object) array('CODE' => 'SYP ','SYMBOL' =>'','TEXT' => 'Syria, Pound');
	$currencies[] = (object) array('CODE' => 'TWD ','SYMBOL' =>'','TEXT' => 'Taiwan, New Dollar');
	$currencies[] = (object) array('CODE' => 'TJS ','SYMBOL' =>'','TEXT' => 'Tajikistan, Somoni');
	$currencies[] = (object) array('CODE' => 'RUB ','SYMBOL' =>'','TEXT' => 'Tajikistan, Russia Ruble');
	$currencies[] = (object) array('CODE' => 'TZS ','SYMBOL' =>'','TEXT' => 'Tanzania, Shilling');
	$currencies[] = (object) array('CODE' => 'THB ','SYMBOL' =>'','TEXT' => 'Thailand, Baht');
	$currencies[] = (object) array('CODE' => 'XOF ','SYMBOL' =>'','TEXT' => 'Togo, CFA Franc BCEAO');
	$currencies[] = (object) array('CODE' => 'NZD ','SYMBOL' =>'','TEXT' => 'Tokelau, New Zealand Dollar');
	$currencies[] = (object) array('CODE' => 'TOP ','SYMBOL' =>'','TEXT' => 'Tonga, Pa\'anga');
	$currencies[] = (object) array('CODE' => 'MDL ','SYMBOL' =>'','TEXT' => 'Transnistria, Moldova Leu');
	$currencies[] = (object) array('CODE' => 'TTD ','SYMBOL' =>'','TEXT' => 'Trinidad and Tobago, Dollar');
	$currencies[] = (object) array('CODE' => 'TND ','SYMBOL' =>'','TEXT' => 'Tunisia, Dinar');
	$currencies[] = (object) array('CODE' => 'TRY ','SYMBOL' =>'','TEXT' => 'Turkey, Lira');
	$currencies[] = (object) array('CODE' => 'TMT ','SYMBOL' =>'','TEXT' => 'Turkmenistan, New Manat');
	$currencies[] = (object) array('CODE' => 'TMM ','SYMBOL' =>'','TEXT' => 'Turkmenistan, Manat');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Turks and Caicos Islands, United States Dollar');
	$currencies[] = (object) array('CODE' => 'AUD ','SYMBOL' =>'','TEXT' => 'Tuvalu, Australia Dollar');
	$currencies[] = (object) array('CODE' => 'TVD ','SYMBOL' =>'','TEXT' => 'Tuvalu, Dollar');
	$currencies[] = (object) array('CODE' => 'UGX ','SYMBOL' =>'','TEXT' => 'Uganda, Shilling');
	$currencies[] = (object) array('CODE' => 'UAH ','SYMBOL' =>'','TEXT' => 'Ukraine, Hryvna');
	$currencies[] = (object) array('CODE' => 'AED ','SYMBOL' =>'','TEXT' => 'United Arab Emirates, Dirham');
	$currencies[] = (object) array('CODE' => 'GBP ','SYMBOL' =>'','TEXT' => 'United Kingdom, Pound');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'United States, Dollar');
	$currencies[] = (object) array('CODE' => 'UYU ','SYMBOL' =>'','TEXT' => 'Uruguay, Peso');
	$currencies[] = (object) array('CODE' => 'UZS ','SYMBOL' =>'','TEXT' => 'Uzbekistan, Som');
	$currencies[] = (object) array('CODE' => 'VUV ','SYMBOL' =>'','TEXT' => 'Vanuatu, Vatu');
	$currencies[] = (object) array('CODE' => 'EUR ','SYMBOL' =>'','TEXT' => 'Vatican City, Euro');
	$currencies[] = (object) array('CODE' => 'VEF ','SYMBOL' =>'','TEXT' => 'Venezuela, Bolivar Fuerte');
	$currencies[] = (object) array('CODE' => 'VND ','SYMBOL' =>'','TEXT' => 'Vietnam, Dong');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Virgin Islands, United States Dollar');
	$currencies[] = (object) array('CODE' => 'USD ','SYMBOL' =>'','TEXT' => 'Wake Island, United States Dollar');
	$currencies[] = (object) array('CODE' => 'XPF ','SYMBOL' =>'','TEXT' => 'Wallis and Futuna Islands, Comptoirs Français du Pacifique Franc');
	$currencies[] = (object) array('CODE' => 'ILS ','SYMBOL' =>'','TEXT' => 'West Bank, Israel New Shekel');
	$currencies[] = (object) array('CODE' => 'JOD ','SYMBOL' =>'','TEXT' => 'West Bank, Jordan Dinar');
	$currencies[] = (object) array('CODE' => 'MAD ','SYMBOL' =>'','TEXT' => 'Western Sahara, Morocco Dirham');
	$currencies[] = (object) array('CODE' => 'WST ','SYMBOL' =>'','TEXT' => 'Samoa, Tala');
	$currencies[] = (object) array('CODE' => 'YER ','SYMBOL' =>'','TEXT' => 'Yemen, Rial');
	$currencies[] = (object) array('CODE' => 'ZMK ','SYMBOL' =>'','TEXT' => 'Zambia, Kwacha');
	$currencies[] = (object) array('CODE' => 'ZWD ','SYMBOL' =>'','TEXT' => 'Zimbabwe, Dollar');

	return $currencies;
}
?>